import argparse
import json
import logging
import os

import pandas as pd

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("evaluate")


def evaluate_forecast_quality(forecast_path: str) -> dict | None:
    if not os.path.exists(forecast_path):
        logger.error("Forecast file not found: %s", forecast_path)
        return None

    df = pd.read_csv(forecast_path)
    df.columns = [c.lower() for c in df.columns]

    if "yhat" not in df.columns:
        logger.error("forecast CSV has no 'yhat' column — was it generated by the pipeline?")
        return None

    has_ci = "yhat_lower" in df.columns and "yhat_upper" in df.columns

    # Sanity checks
    checks = {
        "no_nulls":             not df["yhat"].isnull().any(),
        "non_negative":         (df["yhat"] >= 0).all(),
        "has_confidence_intervals": has_ci,
        # Only check bounds if CI columns exist; avoid KeyError crash
        "sensible_bounds": (
            (df["yhat_upper"] >= df["yhat_lower"]).all() if has_ci else None
        ),
    }

    # We flag if the average exceeds 0.5 (50%) too uncertain for planning.
    uncertainty_index = None
    if has_ci:
        ci_width = df["yhat_upper"] - df["yhat_lower"]
        # Avoid division by zero on any zero forecasts
        nonzero = df["yhat"] != 0
        uncertainty_index = round(
            float((ci_width[nonzero] / df["yhat"][nonzero]).mean()), 4
        ) if nonzero.any() else 0.0

    model_name = df["model"].iloc[0] if "model" in df.columns else "Unknown"

    # Status logic:
    # PASS  — all hard checks pass and uncertainty is within threshold
    # WARN  — checks pass but CI is wide (model uncertain but structurally ok)
    # FAIL  — a hard check failed (nulls, negatives, or inverted bounds)
    hard_checks_pass = all(v for v in checks.values() if v is not None)
    if not hard_checks_pass:
        status = "FAIL"
    elif uncertainty_index is not None and uncertainty_index > 0.5:
        status = "WARN — high uncertainty (CI width > 50% of forecast)"
    else:
        status = "PASS"

    return {
        "model_name":       model_name,
        "forecast_months":  len(df),
        "integrity_checks": checks,
        "summary": {
            "total_forecast":       round(df["yhat"].sum(), 2),
            "avg_monthly_forecast": round(df["yhat"].mean(), 2),
            "peak_month":           df.loc[df["yhat"].idxmax(), "ds"] if "ds" in df.columns else "N/A",
            "peak_forecast":        round(df["yhat"].max(), 2),
            "avg_uncertainty_index": uncertainty_index,
        },
        "status": status,
    }


def compare_to_baseline(current_path: str, baseline_path: str) -> dict | str:
    if not os.path.exists(baseline_path):
        return f"No baseline found at {baseline_path}. Save a known-good forecast there first."

    curr = pd.read_csv(current_path)
    base = pd.read_csv(baseline_path)
    curr.columns = [c.lower() for c in curr.columns]
    base.columns = [c.lower() for c in base.columns]

    if "ds" not in curr.columns or "ds" not in base.columns:
        return "Both CSVs must have a 'ds' column to align by date."

    curr = curr.set_index("ds")["yhat"]
    base = base.set_index("ds")["yhat"]
    common = curr.index.intersection(base.index)

    if len(common) == 0:
        return "No overlapping dates between current and baseline forecast."

    curr_common = curr.loc[common]
    base_common = base.loc[common]

    # MAPE between the two forecasts (treating baseline as "actuals")
    nonzero = base_common != 0
    if not nonzero.any():
        return "Baseline has all-zero values — cannot compute drift."

    drift = float(
        abs(curr_common[nonzero] - base_common[nonzero]).divide(base_common[nonzero]).mean() * 100
    )

    return {
        "months_compared":  len(common),
        "model_drift_mape": round(drift, 2),
        # 10% threshold: below this, differences are likely just re-fitting noise.
        # Above this, a meaningful parameter or data change has occurred.
        "verdict": "STABLE" if drift < 10 else "SIGNIFICANT DRIFT — review before sharing",
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Evaluate pipeline forecast output.")
    parser.add_argument("--results-dir", default="results",
                        help="Directory containing forecast_12m.csv (default: results/)")
    parser.add_argument("--baseline",    default=None,
                        help="Path to a previous forecast CSV for drift comparison")
    args = parser.parse_args()

    forecast_file = os.path.join(args.results_dir, "forecast_12m.csv")

    print("  FORECAST EVALUATION REPORT")

    report = evaluate_forecast_quality(forecast_file)
    if report:
        print(f"\n  Model          : {report['model_name']}")
        print(f"  Status         : {report['status']}")
        print(f"\n  Integrity checks:")
        for k, v in report["integrity_checks"].items():
            if v is None:
                symbol = "—"
            else:
                symbol = "✅" if v else "❌"
            print(f"    {k.replace('_', ' ').title():<30} {symbol}")
        print(f"\n  Forecast summary:")
        for k, v in report["summary"].items():
            print(f"    {k.replace('_', ' ').title():<30} {v}")

    if args.baseline:
        print("\n  Regression comparison:")
        comparison = compare_to_baseline(forecast_file, args.baseline)
        if isinstance(comparison, dict):
            for k, v in comparison.items():
                print(f"    {k.replace('_', ' ').title():<30} {v}")
        else:
            print(f"    {comparison}")

    print()